
int minusOne();
int test_minusOne();
int fitsShort(int);
int test_fitsShort(int);
int isZero(int);
int test_isZero(int);
int isLess(int, int);
int test_isLess(int, int);
int absVal(int);
int test_absVal(int);
int sm2tc(int);
int test_sm2tc(int);
int getByte(int, int);
int test_getByte(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int allOddBits();
int test_allOddBits();
int conditional(int, int, int);
int test_conditional(int, int, int);
int greatestBitPos(int);
int test_greatestBitPos(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
int float_f2i(unsigned);
int test_float_f2i(unsigned);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
